// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsolidadoService.Domain.Entities;

public partial class Consolidado
{
    public int Id { get; set; }

    public DateTime Data { get; set; }

    public decimal Saldo { get; set; }

    public DateTime DataCriacao { get; set; }


}